--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ninjaknights/CameraUtils
build-by-default: true
branches:
- stable-PM5
projects:
  CameraUtils:
    path: ""
    model: virion
    type: library
...
